name: CI

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:

  # test:
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  release:
    # needs: test
    if: ${{ github.actor != 'semantic-release-bot' }}
    uses: ./.github/workflows/release.yml
    secrets: inherit

