# ci.yml
name: CI

on:
  push:
    branches: [main]

jobs:
  # test:
  #   uses: ./.github/workflows/test.yml

  release:
    needs: test
    uses: ./.github/workflows/release.yml

  docker:
    needs: release
    uses: ./.github/workflows/docker.yml
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
