name: Verify and Release
on:
  push:
    branches:
      - main                                        # or master

permissions:
  contents: read                                    # for checkout

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write                               # to be able to publish a GitHub release
      issues: write                                 # to be able to comment on released issues
      pull-requests: write                          # to be able to comment on released pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "21"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx --package semantic-release@25.0.8 \
            --package conventional-changelog-conventionalcommits@8.1.0 \
            --package @semantic-release/exec@7.1.0 \
            --package @semantic-release/git@10.0.1 \
            semantic-release
